name: Build and push Docker Image

on:
  push:
    paths:
      - "Sources/**"
      - ".github/workflows/docker-image.yml" # Trigger on changes to the Dockerfile or source code
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: v1.0.0
      DOCKER_IMAGE_NAME: mikrotik-exporter
      DOCKERFILE: Sources/Mikrotik.Exporter/Dockerfile
    permissions:
      contents: read
      packages: write
    steps:
      - name: check repository
        uses: actions/checkout@v4
        with:
          lfs: "true"

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: Sources
          push: true
          tags: bvdcode/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}
          file: ${{ env.DOCKERFILE }}

      - name: login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push docker image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: Sources
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}
          file: ${{ env.DOCKERFILE }}
